/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geo.detector;

import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;
import java.util.Map;

public class SolverTest {
    @Test
    public void testSolver() throws IOException {
        Map<Integer, String> geo1 = testFile("geo_tag1.tsv");
        Assert.assertEquals(788, geo1.size());
        Map<Integer, String> geo2 = testFile("geo_tag2.tsv");
        Assert.assertEquals(254, geo2.size());
    }

    private Map<Integer, String> testFile(String testFile) throws IOException {
        String file = getClass().getResource("/" + testFile).getFile();
        Map<Integer, String> answer = new Solver().readFromFile(file).Answer();
        for (int id : answer.keySet()) {
            System.out.println(id + " -> " + answer.get(id));
        }
        return answer;
    }
}
